.\" Manpage for roshi. Started 2019-01-07 by Michael Vetter.
.TH man 5  "02 February 2019" "version 0.0" "FILE FORMATS"
.SH NAME
roshi.config - roshi configuration file
.SH DESCRIPTION
roshi(1) is a commandline workout journal.
It looks for its configuration file in the following places: 
 * roshi.conf relative to the binaries path
 * $XDG_CONFIG_HOME/roshi/config
 * ~/.config/roshi/config
.SH INSERT-TEMPLATES
insert-templates are used to tweak the subcommand
.B add
to suit the needs of the user.
.B add
adds a new session to the workout journal. It asks for certain fields which you can store in your journal. Sometimes we don't need all the fields. To save time we can configure insert-templates to make roshi display only certain fields.
.PP
By default all fields get displayed. This is a list of the possible fields that can be omitted:
.PP
insert-template omitall {
  omit_session_place = true
  omit_session_notes = true
  omit_session_feeling = true
  omit_exercise_station = true
  omit_exercise_weight = true
  omit_exercise_sets = true
  omit_exercise_reps = true
  omit_exercise_time = true
  omit_exercise_tempo = true
  omit_exercise_rest = true
  omit_exercise_warmup = true
  omit_exercise_notes = true
  omit_exercise_tags = true
}
.PP
E.g. to track swimming sessions we don't need to track any weights or reps. So we could create an insert-template for swimming:
.PP
insert-template swimming {
  omit_exercise_station = true
  omit_exercise_weight = true
  omit_exercise_sets = true
  omit_exercise_reps = true
}
.SH COMMENTS
One-line comments must start with '#'.
Multi-line comments must start with '/*' and end with '*/'. They must contain an extra '*' in each line between start and end.
.SH AUTHOR
Michael Vetter (jubalh@iodoru.org)
.SH SEE ALSO
roshi(1) 
